---
# Source: single-vm/templates/vm.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-fedora-vm
spec:
  running: true
  template:
    metadata:
      labels:
        debugLogs: "true"
        kubevirt.io/size: small
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        resources:
          requests:
            memory: 1024Mi
            cpu: 1
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: net-1
              bridge: {}
            - name: default
              masquerade: {}
      networks:
        - name: net-1
          multus:
            networkName: net1-cldbr1nondpdk-98
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: "kubevirt/fedora-cloud-container-disk-demo:latest"
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
